[16.0][IMP] sale order carrier auto assign multi-company
camptocamp/sale-workflow pull request #34
Opened 2024-02-21 03:09 UTC by trisdoan

[BSALLO-738](https://jira.camptocamp.com/browse/BSALLO-738)

2024-02-21 07:43 UTC, jbaudoux requested changes

2024-02-21 07:43 UTC, jbaudoux commented on sale_order_carrier_auto_assign/__manifest__.py
> +    "version": "16.0.1.1.0",
Don't modify yourself the version when there is no migration script

2024-02-21 07:43 UTC, jbaudoux commented on sale_packaging_default/__manifest__.py
> +    "version": "16.0.2.1.0",
Same remark here.
Change to this module should not be part of this PR but in another separate one

2024-02-22 03:59 UTC, trisdoan commented
Hi @jbaudoux, thank you for comment. I took into account your remarks.
I removed commits which do not belong to the PR

2024-02-22 08:26 UTC, jbaudoux approved these changes

2024-02-22 08:34 UTC, jbaudoux reviewed
Can you target your PR to OCA. This is not a fix on the PR you are targeting but another fix on the codebase.

Refrain to modify generated files in your PRs so that it can be merged more easily

2024-02-22 08:34 UTC, jbaudoux commented on sale_order_carrier_auto_assign/README.rst
> +* Tris Doan <tridm@trobz.com>
Can you drop changes to README in the PR?

2024-02-22 08:34 UTC, jbaudoux commented on sale_order_carrier_auto_assign/static/description/index.html
> +<li><a class="reference internal" href="#maintainers" id="toc-entry-6">Maintainers</a></li>
Can you drop changes to index in the PR ?

2024-02-22 08:34 UTC, jbaudoux commented on sale_order_carrier_auto_assign/readme/CONTRIBUTORS.rst
> +* Tris Doan <tridm@trobz.com>
Just to prevent a conflict with other PR
```suggestion
* Tris Doan <tridm@trobz.com>
* Phuc (Tran Thanh) <phuc@trobz.com>
```

2024-02-23 08:00 UTC, trisdoan commented
superseded by https://github.com/OCA/sale-workflow/pull/2976

2024-02-23 13:24 UTC, closed without merging